version: "3"

networks: 
  rede_frank_students:
    driver: bridge

volumes: 
  postgres:

services:
  db:
    image: postgres:13
    container_name: db
    restart: always 
    ports:
      - 2345:5432
    networks:
      - rede_frank_students
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db 
    networks:
      - rede_frank_students
    volumes:
      - .:/usr/src/
    env_file:
      - .env 